apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: cluster-service-broker
spec:
  # Points to the endpoint of a service broker
  # The following comments are about the url
  # service-broker: The name of service in service.yaml
  # default: The name of namespace in service.yaml
  # svc.cluster.local: The domain name used by defaut to access to service
  # 12345: The port of service in service.yaml
  url: http://service-broker.default.svc.cluster.local:12345
  authInfo:
    basic:
      secretRef:
        name: "service-broker-auth-secret"
        namespace: default
