kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-auth-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  username: {{ b64enc .Values.brokerConfig.username }}
  password: {{ b64enc .Values.brokerConfig.password }}
