apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: cluster-service-broker
spec:
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}
  authInfo:
    basic:
      secretRef:
        name: "{{ template "fullname" . }}-auth-secret"
        namespace: {{ .Release.Namespace | quote }}
